from __future__ import annotations

from ..models.stats import (
    FEATURE_SCHEMA,
    LABEL_SIZE_FEATURE_NAMES,
    REGION_POOL_STAT_NAMES,
    StatsPredictionModel,
    TransUNetEncoderAdapter,
    build_stats_model,
    infer_encoder_channels,
    load_transunet_from_checkpoint,
    masked_pool_stats_by_label,
)
from .inference import (
    PREDICTED_STATS_LONG_FILENAME,
    PREDICTED_STATS_LOG_FILENAME,
    PREDICTED_STATS_PROVENANCE_FILENAME,
    PREDICTED_STATS_WIDE_FILENAME,
    ScaleSurferStatsPredictor,
    load_stats_feature_matrix,
    load_stats_features,
    resolve_stats_config_path,
    resolve_stats_checkpoint_path,
    stats_long_to_wide,
    stats_repo_name,
    write_stats_outputs,
)
from ..training.stats.train import (
    TrainResult,
    checkpoint_payload,
    evaluate_stats_model,
    latest_stage_checkpoint,
    masked_huber_loss,
    run_stats_epoch,
    train_stats_stage,
)
from .utils import (
    APARC_REGIONS,
    APARC_STATS_NAMES,
    APARC_TABLE_COLUMNS,
    DEFAULT_STATS_RELPATHS,
    GLOBAL_STATS_NAMES,
    OPTIONAL_STATS,
    REQUIRED_STATS,
    TARGET_VALUE_RANGES,
    VOLUME_TABLE_COLUMNS,
    StatsFeatureDataset,
    StatsTensorDataset,
    allowed_table_columns,
    build_openneuro_stats_rows,
    build_target_long_table,
    build_target_matrix,
    build_v8_stats_rows,
    collate_stats_batch,
    columns_by_group,
    combine_sample_rows,
    derive_fs_major_by_dataset_from_checkpoints,
    extract_dataset_id,
    flatten_stats_file,
    group_for_target,
    load_or_build_pooled_feature_cache,
    load_split,
    load_volume_tensor,
    make_stats_feature_loader,
    make_stats_loader,
    measure_for_target,
    pooled_feature_cache_path,
    row_key_from_stats_table,
    safe_name,
    sanitize_target_matrix,
    save_json,
    select_target_columns,
    strip_compile_prefix,
    target_is_supported,
    target_normalization,
    target_parts,
    target_value_range,
)

__all__ = [name for name in globals() if not name.startswith("_")]
